### PR TITLE
Fix upstream deps to point to hashicorp, formerly mitchellh

### PR DESCRIPTION
**Pull request by CpuID**
Repo org was transferred sometime around 2015-2016~ from memory.

### CODE REVIEW

**Comment by CpuID** [comment]
Without this you get weird build failures due to `RenderFilter`

**Comment by apparentlymart** [comment]
Hi @CpuID! Thanks for updating this.

As you may have noticed, this repository has been essentially ignored since 2015, so it's lagging behind on some things. The tests also failed here because Go 1.4 was current when this was originally developed and at least one dependency is using the new `context` package. :confounded: 

I'm going to merge this since it does seem like a good change, but I would also warn that the code in this repository is not really maintained since the team that created it is now using a different workflow that does not depend on rendering a template.

**Comment by apparentlymart** [comment]
Actually, I apparently don't have commit access here any longer :grinning: so I'll need to leave you in the capable hands of someone else on the Say Media team!

**Comment by CpuID** [comment]
thx :)

**Pull request merged**
